// <auto-generated />
using System;
using Effort.DB.Layer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Effort.DB.Layer.Migrations
{
    [DbContext(typeof(EffortDbContext))]
    [Migration("20190630180737_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("effort")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Effort.Models.ActivityType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Comment")
                        .HasMaxLength(250);

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("activity_type");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "analyze",
                            Comment = "Анализ задачи",
                            Deleted = false,
                            Name = "Анализ"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "develop",
                            Comment = "Разработка",
                            Deleted = false,
                            Name = "Разработка"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "test",
                            Comment = "Тестирование",
                            Deleted = false,
                            Name = "Тестирование"
                        });
                });

            modelBuilder.Entity("Effort.Models.Timesheet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ActivityTypeId");

                    b.Property<string>("Comment")
                        .HasMaxLength(250);

                    b.Property<DateTime>("Date");

                    b.Property<bool>("Deleted");

                    b.Property<long>("Duration");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 6, 30, 21, 7, 36, 353, DateTimeKind.Local).AddTicks(1777));

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 6, 30, 21, 7, 36, 343, DateTimeKind.Local).AddTicks(965));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<long>("WorkItemId");

                    b.HasKey("Id");

                    b.ToTable("timesheet");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivityTypeId = 1L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(6490),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ActivityTypeId = 1L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8226),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ActivityTypeId = 1L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8240),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            ActivityTypeId = 2L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8243),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            ActivityTypeId = 2L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8245),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            ActivityTypeId = 2L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8247),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            ActivityTypeId = 2L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8248),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            ActivityTypeId = 3L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8251),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            ActivityTypeId = 3L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8253),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            ActivityTypeId = 3L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8255),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            ActivityTypeId = 3L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8256),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            ActivityTypeId = 3L,
                            Comment = "текст",
                            Date = new DateTime(2019, 6, 30, 21, 7, 36, 355, DateTimeKind.Local).AddTicks(8258),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 1L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
