// <auto-generated />
using System;
using Effort.DB.Layer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Effort.DB.Layer.Migrations
{
    [DbContext(typeof(EffortDbContext))]
    [Migration("20190630174605_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("effort")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Effort.Models.ActivityType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment")
                        .HasMaxLength(250);

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("activity_type");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Comment = "Анализ задачи",
                            Deleted = false,
                            Name = "Анализ"
                        },
                        new
                        {
                            Id = 2L,
                            Comment = "Разработка",
                            Deleted = false,
                            Name = "Разработка"
                        },
                        new
                        {
                            Id = 3L,
                            Comment = "Тестирование",
                            Deleted = false,
                            Name = "Тестирование"
                        });
                });

            modelBuilder.Entity("Effort.Models.Timesheet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ActivityTypeId");

                    b.Property<string>("Comment")
                        .HasMaxLength(250);

                    b.Property<DateTime>("Date");

                    b.Property<bool>("Deleted");

                    b.Property<long>("Duration");

                    b.Property<DateTime>("Inserted");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<long>("WorkItemId");

                    b.HasKey("Id");

                    b.ToTable("timesheet");
                });
#pragma warning restore 612, 618
        }
    }
}
