// <auto-generated />
using System;
using Effort.DB.Layer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Effort.DB.Layer.Migrations
{
    [DbContext(typeof(EffortDbContext))]
    partial class EffortDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("effort")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Effort.Models.ActivityType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Comment")
                        .HasMaxLength(250);

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("activity_type");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "analyze",
                            Comment = "Анализ задачи",
                            Deleted = false,
                            Name = "Анализ"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "develop",
                            Comment = "Разработка",
                            Deleted = false,
                            Name = "Разработка"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "test",
                            Comment = "Тестирование",
                            Deleted = false,
                            Name = "Тестирование"
                        });
                });

            modelBuilder.Entity("Effort.Models.Timesheet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ActivityTypeId");

                    b.Property<string>("Comment")
                        .HasMaxLength(250);

                    b.Property<DateTime>("Date");

                    b.Property<bool>("Deleted");

                    b.Property<long>("Duration");

                    b.Property<DateTime>("Inserted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 7, 1, 1, 3, 18, 648, DateTimeKind.Local).AddTicks(2923));

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 7, 1, 1, 3, 18, 642, DateTimeKind.Local).AddTicks(6692));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<long>("WorkItemId");

                    b.HasKey("Id");

                    b.ToTable("timesheet");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivityTypeId = 1L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 655, DateTimeKind.Local).AddTicks(2306),
                            Deleted = true,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 11L
                        },
                        new
                        {
                            Id = 2L,
                            ActivityTypeId = 1L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9603),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 22L
                        },
                        new
                        {
                            Id = 3L,
                            ActivityTypeId = 1L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9654),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 33L
                        },
                        new
                        {
                            Id = 4L,
                            ActivityTypeId = 2L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9659),
                            Deleted = true,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 44L
                        },
                        new
                        {
                            Id = 5L,
                            ActivityTypeId = 2L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9675),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 55L
                        },
                        new
                        {
                            Id = 6L,
                            ActivityTypeId = 2L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9679),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 66L
                        },
                        new
                        {
                            Id = 7L,
                            ActivityTypeId = 2L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9685),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 77L
                        },
                        new
                        {
                            Id = 8L,
                            ActivityTypeId = 3L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9688),
                            Deleted = true,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 88L
                        },
                        new
                        {
                            Id = 9L,
                            ActivityTypeId = 3L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9692),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 99L
                        },
                        new
                        {
                            Id = 10L,
                            ActivityTypeId = 3L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9696),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 100L
                        },
                        new
                        {
                            Id = 11L,
                            ActivityTypeId = 3L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9700),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 110L
                        },
                        new
                        {
                            Id = 12L,
                            ActivityTypeId = 3L,
                            Comment = "текст",
                            Date = new DateTime(2019, 7, 1, 1, 3, 18, 656, DateTimeKind.Local).AddTicks(9703),
                            Deleted = false,
                            Duration = 15L,
                            UserId = "iloer",
                            WorkItemId = 120L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
