using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace effort_extension.tfsObjects.v4
{
    public class Fields
    {
        //Autogenerated class for JSON response
        /// <summary>
        /// 
        /// </summary>
        public string SystemAreaPath { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemTeamProject { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemIterationPath { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemWorkItemType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemState { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemReason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemAssignedTo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemCreatedDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemCreatedBy { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemChangedDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemChangedBy { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemTitle { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemBoardColumn { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemBoardColumnDone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCommonStateChangeDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCommonActivatedDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCommonActivatedBy { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCommonResolvedDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCommonResolvedBy { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCommonResolvedReason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int MicrosoftVSTSCommonPriority { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCommonTriage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int MicrosoftVSTSCommonStackRank { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSBuildIntegrationBuild { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int MicrosoftVSTSSchedulingOriginalEstimate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCMMIBlocked { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCMMIRequirementType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCMMICommitted { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MicrosoftVSTSCMMIUserAcceptanceTest { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WEF_D19A6E4BBC9E41D48C782DDADDFDF55B_KanbanColumn { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WEF_D19A6E4BBC9E41D48C782DDADDFDF55B_KanbanColumnDone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WEF_6C8D986F45DF4EA89D1FB48181FFAE30_KanbanColumn { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WEF_6C8D986F45DF4EA89D1FB48181FFAE30_KanbanColumnDone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemDescription { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ACDescriptionHtml { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SystemTags { get; set; }
    }

    public class Attributes
    {

        /// <summary>
        /// 
        /// </summary>
        public string isLocked { get; set; }
    }

    public class RelationsItem
    {

        /// <summary>
        /// 
        /// </summary>
        public string rel { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string url { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Attributes attributes { get; set; }
    }

    public class Self
    {

        /// <summary>
        /// 
        /// </summary>
        public string href { get; set; }
    }

    public class WorkItemUpdates
    {

        /// <summary>
        /// 
        /// </summary>
        public string href { get; set; }
    }

    public class WorkItemRevisions
    {

        /// <summary>
        /// 
        /// </summary>
        public string href { get; set; }
    }

    public class WorkItemHistory
    {

        /// <summary>
        /// 
        /// </summary>
        public string href { get; set; }
    }

    public class Html
    {

        /// <summary>
        /// 
        /// </summary>
        public string href { get; set; }
    }

    public class WorkItemType
    {

        /// <summary>
        /// 
        /// </summary>
        public string href { get; set; }
    }

    public class _Fields
    {

        /// <summary>
        /// 
        /// </summary>
        public string href { get; set; }
    }

    public class _links
    {

        /// <summary>
        /// 
        /// </summary>
        public Self self { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public WorkItemUpdates workItemUpdates { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public WorkItemRevisions workItemRevisions { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public WorkItemHistory workItemHistory { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Html html { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public WorkItemType workItemType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public _Fields fields { get; set; }
    }

    public class WorkItem
    {

        /// <summary>
        /// 
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int rev { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Fields fields { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public List<RelationsItem> relations { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public _links _links { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string url { get; set; }
    }

    public class Root
    {

        /// <summary>
        /// 
        /// </summary>
        public WorkItem WorkItem { get; set; }
    }



}